# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    image: alessmicro/mariadb:11.4-ol9-amd64-testing
    container_name: mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_joomla
      - MARIADB_DATABASE=bitnami_joomla
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  joomla:
#    image: docker.io/bitnami/joomla:5
    image: alessmicro/joomla:4-amd64
    container_name: joomla
    ports:
      - '8080:8080'
      - '4443:8443'
    environment:
      - JOOMLA_DATABASE_HOST=mariadb
      - JOOMLA_DATABASE_PORT_NUMBER=3306
      - JOOMLA_DATABASE_USER=bn_joomla
      - JOOMLA_DATABASE_NAME=bitnami_joomla
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'joomla_data:/bitnami/joomla'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  joomla_data:
    driver: local
