# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'
services:
  mariadb:
    container_name: mariadb
    image: docker.io/bitnami/mariadb:latest
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_drupal
      - MARIADB_DATABASE=bitnami_drupal
    volumes:
      - './mariadb_data:/bitnami/mariadb:Z'
  drupal:
    container_name: drupal
    tty: true
#    image: docker.io/bitnami/drupal-nginx:10
#    image: alessmicro/drupal:10-php83-nginx-official
    image: alessmicro/drupal-nginx:10-php83-nginx
    ports:
      - '8080:8080'
#     - '443:8443'
    environment:
      - DRUPAL_DATABASE_HOST=mariadb
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_USER=bn_drupal
      - DRUPAL_DATABASE_NAME=bitnami_drupal
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './drupal_data:/bitnami/drupal:Z'
    depends_on:
      - mariadb
#    entrypoint: ["/bin/bash"]
#volumes:
#  mariadb_data:
#    driver: local
#  drupal_data:
#    driver: local
